### PR TITLE
Add GitHub actions to run unit tests

### PR DESCRIPTION
**Pull request by ilhs1096069**
We've been dealing with a bunch of issues with committing to the project without having working code, so this will make sure that before it gets to main, it'll get tested and if there's any issues, they'll need to be resolved before pushing to main.

### CODE REVIEW

**Comment by ilhs1096069** [comment]
This can potentially be expanded later to also run unit tests within Unity but for now we just need to test Core

**Review by roguefirework — APPROVED** [review]
I don't github actions, I didn't look at the changes, so I say we merge and pray. LGTM!

**Review by 1118422ILHS — APPROVED** [review]
looks bad to me

**Comment by 1118422ILHS** [comment]
They refuse to test the actions before merging, but honestly the expected value of merging blindly is still positive

**Comment by 1118422ILHS** [comment]
remember to squash merge!

**Pull request merged**
