### PR TITLE
Adding the testing project to the Solution and fixing the WumpusCore csproj

### PR DESCRIPTION
**Pull request by ilhs1096069**
* I completely forgot to add the Testing project as a project on the solution, so that's been done.
* The "StoredHighScore" file was still on the compile list in the csproj despite being removed a LONG time ago.

### CODE REVIEW

**Review by roguefirework — APPROVED** [review]
Looks good now!

**Review by ilhs1041495 — COMMENTED** [review]
no more stored high score

**Review by ilhs1041495 — APPROVED** [review]

**Review by 1118422ILHS — APPROVED** [review]
Thanks! now i can write code again

**Comment by ilhs1096069** [comment]
The testing project is a .net 7.0 project, and we need to be compatible with WumpusCore and Unity which are both on an older version. So I'm closing this for now and will make a new Testing project with the right version

**Pull request closed without merging**
