### PR TITLE
Stub Entity

### PR DESCRIPTION
**Pull request by 1118422ILHS**
Entity/Mover are helper classes for all moving game elements.

### CODE REVIEW

**Comment by 1118422ILHS** [comment]
I will wait until all 4 requests have approved, as those include those who work on Controller, GameLocations, Topology, Player, and Wumpus.

**Review by havecookies — APPROVED** [review]
probably fine

**Review by MaximumMaxxx — CHANGES_REQUESTED** [review]
Make entity and abstract class or interface or something 
image

**Review by ilhs1096069 — APPROVED** [review]
Looks pretty ok

**Review by ILHS2000503 — APPROVED** [review]
looks like code to me

**Review by MaximumMaxxx — CHANGES_REQUESTED** [review]
- On check if adjacent make it clear what failing means
- Get rid of all the "cref='NotImplmentedException'" thingies

**Review by MaximumMaxxx — CHANGES_REQUESTED** [review]
Also update the docs on moveToRoom to be clearer, either an exception tag or something else

**Review by MaximumMaxxx — APPROVED** [review]

**Comment by MaximumMaxxx** [comment]
Yipee

**Pull request merged**
