### PR TITLE
Remove OBJ files from Testing

### PR DESCRIPTION
**Pull request by ilhs1096069**
Reverts thewumper/Wumpus#16

Merged with an OBJ folder with build info, get that out before testing is merged again

### CODE REVIEW

**Comment by ilhs1096069** [comment]
@MaximumMaxxx >:(

**Comment by roguefirework** [comment]
LGTM!

**Review by roguefirework — CHANGES_REQUESTED** [review]
Why are we reverting just delete obj/Debug/net7.0 lol

**Review by roguefirework — APPROVED** [review]
Looks good to me!

**Pull request merged**
