### PR TITLE
ints -> uints in Player.cs

### PR DESCRIPTION
**Pull request by havecookies**

### CODE REVIEW

**Comment by 1118422ILHS** [comment]
Unsigned is not necessary here, it will never make a difference, and may break code which depends on this.

**Comment by 1118422ILHS** [comment]
Please close the PR.

**Comment by ilhs1096069** [comment]
> Unsigned is not necessary here, it will never make a difference, and may break code which depends on this.

There's no code that depends on this at the moment. It makes sense to have uints as you can never have negative coins.

**Review by ilhs1096069 — APPROVED** [review]
Nothing depends on this, so it's a harmless change that makes sense

**Review by ilhs1041495 — APPROVED** [review]

**Review by 1118422ILHS — APPROVED** [review]
Approve. Better for ensuring code stays within bounds, and memory use doesn't matter here. You could even use a long if you wanted (DON'T.)

**Pull request merged**
